version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      # Pass all to allow nginx proxy requests into index.php or node instance
      - ./:/var/www
      # Logs volume
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      # Nuxt port
      - 8080:80
      # Laravel port
      - 8081:81
    links:
      - node
      - php-fpm
    networks:
      - internal

  # PHP FastCGI Process Manager container
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    #    links:
    #      - mysql
    #      - redis
    #      - mailhog
    networks:
      - internal

  # Node container
  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./client:/var/www/client
    networks:
      - internal

  # PostgreSQL
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  # Redis container
  redis:
    build:
      context: docker/redis
      dockerfile: Dockerfile
    volumes:
      - redis:/data
    ports:
      - 63791:6379
    networks:
      - internal

  # PHP Command line
  php-cli:
    build:
      context: docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    #    links:
    #      - mysql
    #      - redis
    #      - mailhog
    tty: true
    networks:
      - internal

######### Volumes ###################################

volumes:
  mysql:
    driver: local
  redis:
    driver: local

######### Networks ###################################

networks:
  internal:
    driver: bridge
